name: stichanda_driver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  shimmer_animation: ^2.2.2
  flutter_switch: ^0.3.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  geolocator: ^14.0.2
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dotted_border: ^2.1.0
  image_picker: ^1.2.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900